version: "3.4"
services:
  approver:
    build:
      context: .
      dockerfile: ./docker/dockerfiles/Dockerfile.approver
      target: production
    ports:
      - "3020:3020"
    restart: always  
    volumes:
      - ./app.env:/app/apps/approver/.env
      - ./dat:/app/apps/approver/dat
      - ./refresh:/app/apps/approver/refresh
      - ./wallet:/app/apps/approver/wallet
      - ./sk:/app/apps/approver/sk
      - ./enc:/app/apps/approver/enc
      - ./whitelist:/app/apps/approver/whitelist