version: "3.4"
services:
  approver:
    build:
      context: .
      dockerfile: ./docker/dockerfiles/Dockerfile.approver
      target: production
    ports:
      - "3020:3020"
    volumes:
      - ./dat:/app/apps/approver/dat
      - ./refresh:/app/apps/approver/refresh
      - ./wallet:/app/apps/approver/wallet