version: "3.4"
services:
  approver:
    build:
      context: .
      dockerfile: ./docker/dockerfiles/Dockerfile.approver
      target: production
      tags: 
        - europe-west1-docker.pkg.dev/inabit-mgmt/apps-eu/approver:latest
    volumes:
      - ./dat:/app/apps/approver/dat
      - ./refresh:/app/apps/approver/refresh
    ports:
      - "3020:3020"
    env_file:
      - ./.env